version: '3.8'

services:
  redis:
    image: redis:6.2
    networks:
      - backend

  worker:
    image: localhost:5000/celery_worker:latest
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - backend
    volumes:
      - ./log_file.txt:/app/log_file

networks:
  backend:
