version: '3.8'

services:
  redis:
    image: redis:6.2
    networks:
      - backend

  worker:
    image: registry.gitlab.com/mtvp/celery_task:latest
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
