version: '3.8'

services:
  redis:
    image: redis:6.2
    networks:
      - backend

  worker:
    image: localhost:5000/celery_worker:latest
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
    networks:
      - backend

  trigger:
    image: localhost:5000/celery_worker:latest
    command: ["python", "trigger_task.py"]
    depends_on:
      - redis
      - worker
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

networks:
  backend:
