version: '3.8'

services:
  worker:
    image: registry.gitlab.com/mtvp/celery_task:latest
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true