version: '3.8'

services:
  redis:
    image: redis:6.2
    network_mode: host
#    networks:
#      - backend

  worker:
    image: localhost:5000/celery_worker:latest
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    network_mode: host
#    networks:
#      - backend

#networks:
#  backend:
