version: '3.8'

services:
  redis:
    image: redis:6.2
    networks:
      - backend

  postgres:
    image: postgres:13
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MAX_CONNECTIONS: 500
    ports:
      - "5432:5432"
    networks:
      - backend
    command: ["postgres", "-c", "max_connections=500"]

  worker:
    build:
      context: .
      dockerfile: DockerfileLocal
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
    env_file:
      - .env.local
    networks:
      - backend

networks:
  backend:
